// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/badge-variants/DotSeparator.tsx": () => import("../components/mockups/badge-variants/DotSeparator.tsx"),
  "./components/mockups/badge-variants/Eyebrow.tsx": () => import("../components/mockups/badge-variants/Eyebrow.tsx"),
  "./components/mockups/badge-variants/Stamp.tsx": () => import("../components/mockups/badge-variants/Stamp.tsx"),
  "./components/mockups/badge-variants/Underline.tsx": () => import("../components/mockups/badge-variants/Underline.tsx")
};
